version: "3.9"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMe
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: salim
      MYSQL_PASSWORD: ChangeMe
    volumes:
      - data:/var/lib/mysql
volumes:
  data: {}
